const data = [
  {
    id: 1,
    location: 'Berlin',
    category: 'Sedan',
    transmisson: 'Automatic',
    price: 150,
    make: 'Audi',
    model: 'A6',
    model_year: 2016,
    color: 'Black',
    seats: '5',
    doors: '5 Doors',
    plate_number: 'B 69 STF',
    rate: '4',
    starus: 'available',
    horsepower: '313',
    owner: 'Isus',
  },
  {
    id: 2,
    location: 'Paris',
    category: 'Sedan',
    price: 100,
    transmisson: 'Manual',
    make: 'Toyota',
    model: 'Camry',
    model_year: 2020,
    color: 'blue',
    seats: '5',
    doors: '5 Doors',
    plate_number: 'B 12 BLN',
    rate: '4',
    starus: 'available',
    horsepower: '180',
    owner: 'Marius',
  },
  {
    id: 3,
    category: 'Sport',
    location: 'Bucuresti',
    price: 100,
    make: 'BMW',
    transmisson: 'Automatic',
    model: 'M3',
    model_year: 2019,
    color: 'red',
    seats: '4',
    doors: '3 Doors',
    plate_number: 'B 10 BOS',
    rate: '3,5',
    starus: 'available',
    horsepower: '350',
    owner: 'Iuda',
  },
];
module.exports = data;
