const data = [
  {
    id: 1,
    location: 'Berlin',
    make: 'Audi',
    model: 'A6',
    model_year: 2016,
    color: 'black',
    seats: '5',
    doors: 5,
    plate_number: 'B 69 STF',
    rate: '4',
    starus: 'available',
    horsepower: 313,
    owner: 'Isus',
  },
  {
    id: 2,
    location: 'Paris',
    make: 'Toyota',
    model: 'Camry',
    model_year: 2020,
    color: 'blue',
    seats: '5',
    doors: 5,
    plate_number: 'B 12 BLN',
    rate: '4',
    starus: 'available',
    horsepower: 180,
    owner: 'Marius',
  },
  {
    id: 3,
    location: 'Bucuresti',
    make: 'BMW',
    model: 'M3',
    model_year: 2019,
    color: 'red',
    seats: '4',
    doors: 3,
    plate_number: 'B 10 BOS',
    rate: '3,5',
    starus: 'available',
    horsepower: 350,
    owner: 'Iuda',
  },
];
module.exports = data;
